# Generated by Django 3.0.4 on 2020-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('sup_title', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('text_button', models.CharField(blank=True, max_length=64, null=True)),
                ('url_button', models.SlugField(max_length=512)),
                ('is_slider', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=False)),
            ],
        ),
    ]
