# Generated by Django 3.0.4 on 2020-03-22 14:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-date_publicate'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='feed',
            name='date_publicate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 22, 17, 54, 49, 624666), null=True, verbose_name='Опубликовать после'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='body',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='is_slider',
            field=models.BooleanField(default=False, verbose_name='Слайдер'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Ссылка на новость'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='sup_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='text_button',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Надпись кнопки'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url_button',
            field=models.SlugField(max_length=512, verbose_name='Ссылка кнопки'),
        ),
    ]
