# Generated by Django 3.0.4 on 2020-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200322_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='date_published',
        ),
        migrations.AddField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовать после'),
        ),
        migrations.AddField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовать после'),
        ),
    ]
