# Generated by Django 3.0.4 on 2020-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200322_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовать до'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url_button',
            field=models.SlugField(blank=True, max_length=512, null=True, verbose_name='Ссылка кнопки'),
        ),
    ]
