# Generated by Django 3.0.4 on 2020-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200322_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Заголовок'),
        ),
    ]
