# Generated by Django 3.0.4 on 2020-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200322_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_blog',
            field=models.BooleanField(default=False, verbose_name='Блог'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='body',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='sup_title',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='text_button',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Надпись кнопки'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url_button',
            field=models.SlugField(blank=True, default='', max_length=512, verbose_name='Ссылка кнопки'),
        ),
    ]
