# Generated by Django 3.0.4 on 2020-03-23 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200322_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Название бренда')),
                ('image', models.ImageField(upload_to='media/OurBrands', verbose_name='Логотип')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Наши бренды',
                'verbose_name_plural': 'Наши бренды',
                'ordering': ['-order'],
            },
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 15, 58, 26, 544179), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 30, 15, 58, 26, 544179), null=True, verbose_name='Опубликовать до'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Заголовок'),
        ),
    ]
