# Generated by Django 3.0.4 on 2020-03-24 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200323_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourbrand',
            options={'ordering': ['order'], 'verbose_name': 'Наши бренды', 'verbose_name_plural': 'Наши бренды'},
        ),
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='body',
            field=models.CharField(blank=True, default='', max_length=10000, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 24, 16, 15, 13, 125726), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 31, 16, 15, 13, 125726), null=True, verbose_name='Опубликовать до'),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='image',
            field=models.ImageField(upload_to='OurBrands/', verbose_name='Логотип'),
        ),
    ]
