# Generated by Django 3.0.4 on 2020-03-25 13:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200325_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_publicate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='body',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 25, 16, 18, 38, 187115), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 1, 16, 18, 38, 187115), null=True, verbose_name='Опубликовать до'),
        ),
    ]
