# Generated by Django 3.0.4 on 2020-03-28 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200325_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Ссылка на категорию')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_publicate'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 15, 57, 5, 295963), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 4, 15, 57, 5, 295963), null=True, verbose_name='Опубликовать до'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, default='default_img/news.jpeg', null=True, upload_to='Feed/%Y/%m/%d/%H', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='image',
            field=models.ImageField(upload_to='OurBrands/%Y/%m/%d/%H', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CategoryFeed', verbose_name='Категория'),
        ),
    ]
