# Generated by Django 3.0.4 on 2020-03-29 09:35

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200328_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoryFeed', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 29, 12, 35, 37, 372750), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 5, 12, 35, 37, 372750), null=True, verbose_name='Опубликовать до'),
        ),
    ]
