# Generated by Django 3.0.4 on 2020-04-01 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200401_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 1, 17, 23, 50, 311130), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 8, 17, 23, 50, 311130), null=True, verbose_name='Опубликовать до'),
        ),
    ]
