# Generated by Django 3.0.4 on 2020-04-05 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200404_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 5, 16, 40, 57, 265804), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 16, 40, 57, 266804), null=True, verbose_name='Опубликовать до'),
        ),
    ]
