# Generated by Django 3.0.4 on 2020-04-05 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200405_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 5, 13, 59, 52, 747231, tzinfo=utc), null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 13, 59, 52, 747231, tzinfo=utc), null=True, verbose_name='Опубликовать до'),
        ),
    ]
