# Generated by Django 3.0.4 on 2020-04-05 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200405_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Опубликовать c'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Опубликовать до'),
        ),
    ]
