# Generated by Django 3.0.4 on 2020-04-05 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200405_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 14, 5, 4, 392882, tzinfo=utc), null=True, verbose_name='Опубликовать до'),
        ),
    ]
