# Generated by Django 3.0.4 on 2020-04-05 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200405_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 18, 2, 51, 493735, tzinfo=utc), null=True, verbose_name='Опубликовать до'),
        ),
    ]
