# Generated by Django 3.0.4 on 2020-04-26 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200426_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 11, 24, 14, 656505, tzinfo=utc), null=True, verbose_name='Опубликовать до'),
        ),
    ]
