# Generated by Django 3.0.4 on 2020-08-12 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200426_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 19, 22, 48, 1, 441737, tzinfo=utc), null=True, verbose_name='Опубликовать до'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, default='default_img/news.jpeg', null=True, upload_to='wrap', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ourbrand',
            name='image',
            field=models.ImageField(upload_to='wrap', verbose_name='Логотип'),
        ),
    ]
