# Generated by Django 3.0.4 on 2020-08-12 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200813_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 19, 23, 1, 49, 377623, tzinfo=utc), null=True, verbose_name='Опубликовать до'),
        ),
    ]
