# Generated by Django 3.2.5 on 2021-07-24 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_feed_date_published_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 20, 13, 44, 816702, tzinfo=utc), null=True, verbose_name='Опубликовать до'),
        ),
    ]
