# Generated by Django 3.0.4 on 2021-08-14 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_feed_date_published_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 20, 3, 36, 67197), null=True, verbose_name='Опубликовать до'),
        ),
    ]
