# Generated by Django 3.0.4 on 2021-08-14 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20210814_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 20, 9, 48, 186916), null=True, verbose_name='Опубликовать до'),
        ),
    ]
