# Generated by Django 3.0.4 on 2022-02-25 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20210814_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_published_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 21, 27, 51, 60583), null=True, verbose_name='Опубликовать до'),
        ),
    ]
