# Generated by Django 3.0.4 on 2021-08-14 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Ссылка категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.Category', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Купон')),
                ('discount', models.PositiveIntegerField(max_length=100, verbose_name='Скидка %')),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма активации')),
                ('quantity_activation', models.PositiveIntegerField(verbose_name='Количество активаций')),
                ('active_from', models.DateTimeField(verbose_name='Активен от')),
                ('active_to', models.DateTimeField(verbose_name='Активен до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('order_notes', models.CharField(blank=True, max_length=512, verbose_name='Примечания к заказу')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен заказ')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.Coupon')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название товара')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание товара')),
                ('preview_image', models.ImageField(blank=True, default='default_img/product.jpg', null=True, upload_to='wrap', verbose_name='Изображения для предпросмотра')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка на товар')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по скидке')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество товара')),
                ('date_publicate', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления товара')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа товара')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('count_views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('count_buys', models.PositiveIntegerField(default=0, verbose_name='Количество покупок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', '-date_publicate'],
            },
        ),
        migrations.CreateModel(
            name='SpecialCategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('type_slider', models.CharField(choices=[('row1', 'Строка тип 1'), ('row2', 'Строка тип 2'), ('grid', 'Сетка')], max_length=16, verbose_name='Тип слайдера')),
                ('product', models.ManyToManyField(related_name='special_categories', to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Специальная категория',
                'verbose_name_plural': 'Специальные категории',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wrap', verbose_name='Изображения товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('date_publicate', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date_publicate'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Оформленный товар',
                'verbose_name_plural': 'Оформленные товары',
                'ordering': ['-date_create'],
            },
        ),
    ]
